// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProductMicroservice.Models;

#nullable disable

namespace StudentProductMicroservice.Migrations
{
    [DbContext(typeof(StudentProductContext))]
    partial class StudentProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentProductMicroservice.Models.StudentProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("StudentProducts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StudentProduct");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.Grant", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.StudentProduct");

                    b.HasDiscriminator().HasValue("Grant");
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.Loan", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.StudentProduct");

                    b.HasDiscriminator().HasValue("Loan");
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.BasicGrant", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.Grant");

                    b.HasDiscriminator().HasValue("BasicGrant");
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.SupplementaryGrant", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.Grant");

                    b.HasDiscriminator().HasValue("SupplementaryGrant");
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.TravelProduct", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.Grant");

                    b.Property<bool>("IsWeek")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("TravelProduct");
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.InterestBearingLoan", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.Loan");

                    b.HasDiscriminator().HasValue("InterestBearingLoan");
                });

            modelBuilder.Entity("StudentProductMicroservice.Models.TuitionFeesLoan", b =>
                {
                    b.HasBaseType("StudentProductMicroservice.Models.Loan");

                    b.HasDiscriminator().HasValue("TuitionFeesLoan");
                });
#pragma warning restore 612, 618
        }
    }
}
